jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
    - uses: bahmutov/npm-install@v1
    - run: bash ./ci.sh
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: CI
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
name: CI
on:
  pull_request: {}
  push: {}
